### ISSUE TITLE
报错：`OtherClientOnlineEvent` 不是 `Event` 的子类

### ISSUE THREAD

**Issue by keuin** [YiriMiraiProject/YiriMirai#27]
yiri-mirai版本：0.2.4.2（目前pypi的最新版）

控制台会有不少这样的错误消息：
```
[ERROR][2021-09-11 22:53:48,945][base_events.py][1738] Task exception was never retrieved
future: <Task finished name='Task-22' coro=<Adapter.emit() done, defined at X:\some\path\lib\site-packages\mirai\adapters\base.py:174> exception=ValueError('`OtherClientOnlineEvent` 不是 `Event` 的子类！')>
Traceback (most recent call last):
  File "X:\some\path\lib\site-packages\mirai\adapters\base.py", line 183, in emit
    return sum(await asyncio.gather(*coros), [])
  File "X:\some\path\lib\site-packages\mirai\bus.py", line 187, in emit
    for m_event in self.event_chain_generator(event):
  File "X:\some\path\lib\site-packages\mirai\models\bus.py", line 23, in event_chain_parents
    event_type = Event.get_subtype(event)
  File "X:\some\path\lib\site-packages\mirai\models\base.py", line 90, in get_subtype
    raise ValueError(f'`{name}` 不是 `{cls.__name__}` 的子类！')
ValueError: `OtherClientOnlineEvent` 不是 `Event` 的子类！
```

看起来在其他客户端登录了bot的QQ时，会出现这个错误。

**Comment by Wybxc** [comment]
0.2.4.3 已发布，修复该问题。
